### PR TITLE
warnings: replace bs with mel

### PR DESCRIPTION
**Pull request by jchavarri**
Partially tackles #747 (still not fixing the appearances of `@bs` in type errors that @davesnx mentioned).

Companion PR of https://github.com/melange-re/melange-compiler-libs/pull/29/.

### CODE REVIEW

**Comment by jchavarri** [comment]
opam ci build is ok but the nix one is failing for some reason.

**Comment by anmonteiro** [comment]
> opam ci build is ok but the nix one is failing for some reason.

Probably just needs a `nix flake update` (when we change compiler libs -- and probably warrants mentioning this in `CONTRIBUTING.md` too -- I'll do it)

**Comment by anmonteiro** [comment]
> probably warrants mentioning this in `CONTRIBUTING.md`

Check https://github.com/melange-re/melange/pull/802

**Comment by jchavarri** [comment]
Thanks for #802. Unfortunately my local nix installation broke for some reason. I don't have the `nix` exe available anymore, and the `.nix-profile` symlink is pointing to a file that no longer exists. I will try to fix it eventually, but in the meantime I'm unable to test the fix you recommended in that PR.

**Comment by anmonteiro** [comment]
no worries. we need to get https://github.com/melange-re/melange-compiler-libs/pull/29 merged before that, anyway. will work on reviewing it first.

**Review by anmonteiro — APPROVED** [review]

**Pull request merged**
