### PR TITLE
Experimental: don't write a `.bsbuild`

### PR DESCRIPTION
**Pull request by anmonteiro**
This change removes the need for writing down a `.bsbuild` "database" of a project's modules and source directories.

Instead, `bsb_helper` now gets passed a list of include directories corresponding to the sources declared in `bsconfig.json`.

### This is experimental, why?

TL;DR it currently degrades performance in large projects.

If a project has many source directories, we're basically telling Dune to scan all of them to search the single artifact that we need, for _every_ target. This can become slow very quickly.

I still don't know how to get around this, but I wanted to get some prototyping done, hence this PR.

### CODE REVIEW

**Comment by anmonteiro** [comment]
After 5331e9a, this is now a little faster than the first commit, but I think it's still a little slower than the current HEAD.

**Comment by johnhaley81** [comment]
I think I might need to get off my butt and finally pull in melange to our repo. We have a very large project that this might have a big effect on. How urgent is this?

**Comment by anmonteiro** [comment]
This is not urgent at all. I just wanted to save my work so I opened the PR.

I'll be exploring alternatives to make this faster soon.

**Comment by TheSpyder** [comment]
I won’t be able to do a good comparison test with my large project until next week when I’m back at work. On my M1 it’s not a fair comparison because ReScript uses intel binaries and melange compiles as native.

**Comment by anmonteiro** [comment]
> I assume we’re talking about startup time with this change?

No, I think this actually impacts build time, as there's more work `bsb_helper` is doing.

**Comment by anmonteiro** [comment]
This is slower than acceptable. I'll think about further experimentation.

**Pull request closed without merging**
