### PR TITLE
Improve melange installation with directory targets

### PR DESCRIPTION
**Pull request by anmonteiro**
Additionally:
- ~always generate `.js` files in the current directory (same directory as the `.cmj`)~
  - there was previously support for writing the `.js` files in another directory (specified through `--bs-package-output`)
  - we gain the flexibility to generate JS files in a directory but "pretend" they are in another (according to where the generated require paths are relative to) 
  - this, in turn, allows us to remove a few "non-standard" (not in OCaml) CLI flags (`--make-runtime` and `--make-runtime-test`)
- the melange runtime tests now also exercise the `mel` CLI, and they're moved to their own package
- Build the melange runtime + stdlib using melange
  - this exercises the `workspace` feature in `bsconfig.json` to build the melange runtime / stdlib
- Melange runtime ES6 files are now distributed with the `.mjs` extension

TODOs:

- [x] Fix esy installation script
- [x] Fix opam installation script

### CODE REVIEW

**Comment by jchavarri** [comment]
> always generate `.js` files in the current directory (same directory as the `.cmj`)

I wonder about the implications of this for the ongoing Dune integration? @rgrinberg suggested to produce both es6 and commonjs versions in separate folders:

> Generate cjs, es6, js rules in separate object directories. For example, for a module `Foo`, the rules would setup js output in `.mylib.objs/{mel.cjs,mel.es6}/foo.js`. 

I understand that with this PR approach, we would produce `cmj` as well in both folders, even if the cmj is the same? e.g. `.mylib.objs/{mel.cjs,mel.es6}/foo.cmj`.

Also, just to be sure, the location of either `cmj` or `js` files has no implications for editor integration, right? As lsp only needs reading `cmi` and `cmt*` files.

**Comment by rgrinberg** [comment]
> Also, just to be sure, the location of either cmj or js files has no implications for editor integration, right? As lsp only needs reading cmi and cmt* files.

That's correct.

**Comment by rgrinberg** [comment]
To expand, this is the desired directory layout for dune:

```
.lib.objs/
  mel.cjs/
  mel.es6/
  mel/
```

With this layout, we're able to do two things:

* Maximize use of lazy loading and only setup JS targets we know we're going to use
* Allow the final rules which generate "executables" (shell out to the bundler) to choose which JS modules they want to use
* Allow both es6 and commonjs executables to co-exist in the same workspace and use the same libraries.

**Comment by anmonteiro** [comment]
The layout can be a dune concern, though, right?

It felt a little weird to have the compiler potentially write a file to a location it's not running in. My thought is that you can move the JS files to their own locations as part of build.

You'd still need to set the correct folder structure and package specs flag for the require calls to make sense

**Comment by anmonteiro** [comment]
For the record: this doesn't change anything in how melange currently works. 

This PR is about installing melange itself and compiling its runtime/stdlib

**Comment by rgrinberg** [comment]
IMO, the best interface from a build system's point of view is one that allows us to specify all inputs and outputs explicitly. The OCaml compiler generally doesn't follow this rule for legacy reasons and as a result the rules we have in dune are needlessly complicated in many ways. I don't see why melange should copy these flaws.

**Comment by rgrinberg** [comment]
> This PR is about installing melange itself and compiling its runtime/stdlib

How does melange install its JS artifacts?

**Comment by anmonteiro** [comment]
Before we used an installation script to copy them. This PR uses the new install dir dune support (I'm running off master)

**Comment by rgrinberg** [comment]
Right, but what's the directory layout? Do you install es6 and commonjs articafts? If so, how do you separate them?

**Comment by anmonteiro** [comment]
> IMO, the best interface from a build system's point of view is one that allows us to specify all inputs and outputs explicitly.

That's fair, and I certainly prefer it to be explicit.

Sorta related: I've run into issues in melange where I wanted to output a file to e.g. somewhere in a parent directory, but I can't track this file as a dune target.

**Comment by anmonteiro** [comment]
> Right, but what's the directory layout? Do you install es6 and commonjs articafts? If so, how do you separate them?

lib/es6 and lib/js folders. They're set via --bs-package-specs

**Comment by rgrinberg** [comment]
> Sorta related: I've run into issues in melange where I wanted to output a file to e.g. somewhere in a parent directory, but I can't track this file as a dune target.

That's a bit of a fundamental limitation imposed by dune's lazy loading of rules. If we were to allow rules to introduce targets in their parents, we would need to scan all the children of directory `x` to get the targets under `x`. But we do allow rules to introduce targets in sub directories - although this is not yet available to the dune language.

**Comment by rgrinberg** [comment]
> lib/es6 and lib/js folders. They're set via --bs-package-specs

And thet cmj files live in some 3rd directory?

Okay, that sounds like exactly the structure we want for melange libraries in dune. It would be very convenient if melange's CLI made it easy to generate this structure without copying/moving.

**Comment by anmonteiro** [comment]
> And then cmj files live in some 3rd directory?

in the melange installation, this is the structure:

```bash
$melange_installation_dir/lib
  js/ # Common JS
  es6/ # ES6
  melange/ # .cm{t,i,ti,j} files
```

The melange CLI currently will generate the following for projects (e.g. not in source), for `--bs-package-specs commonjs:./src/subdir:.bs.js --bs-package-specs es6:./src/subdir:.bs.mjs`:


```bash
_build/default/
  src/subdir/
    foo.cmt
    foo.cmi
    foo.cmj
    foo.bs.js
    foo.bs.mjs
```

It would be cool if we could generate e.g., for `--bs-package-specs commonjs:.lib.objs/lib.cjs:.bs.js --bs-package-specs es6:.lib.objs/lib.cjs:.bs.js`:

```bash
_build/default/
  src/subdir/
    mel/
      foo.cmt
      foo.cmi
      foo.cmj
    mel.cjs/
      foo.bs.js
    mel.es6/
      foo.bs.mjs
```

I think this is what we're all saying.

**Comment by anmonteiro** [comment]
> It would be cool if we could generate e.g., for `--bs-package-specs commonjs:.lib.objs/lib.cjs:.bs.js --bs-package-specs es6:.lib.objs/lib.cjs:.bs.js`:
> 
> ```shell
> _build/default/
>   src/subdir/
>     mel/
>       foo.cmt
>       foo.cmi
>       foo.cmj
>     mel.cjs/
>       foo.bs.js
>     mel.es6/
>       foo.bs.mjs
> ```
> 
> I think this is what we're all saying.

This is what the tricky part might be. In fact, I think what we might be looking for is a flat structure for the generated JS files. This is probably possible because all OCaml modules need to be different. It's just that all `require`s need to refer to the same directory. That's what I'm trying to achieve in this current PR by having `--bs-package-specs` control **only** where JS imports are relative to. Before this change, it mixed two concerns: where to output the JS file, and where the JS imports are relative to.

**Comment by rgrinberg** [comment]
A flat directory structure would mean that we would need some sort of naming convention for the js artifacts. Moreover, we would lose out on lazy loading rules. Not the end of the world, but it would be a bit of a shame.

**Comment by anmonteiro** [comment]
Interesting. I suppose we don't need a flat structure at all, then. I suppose the proposal above was good enough (reproduced again below), and we just need to support:

1. Issuing correct relative JS imports (should already be working as long as we pass the correct `--bs-package-specs` flags)
2. support in-source builds through dune promotion. In this case, `_build/default/src/subdir/mel.cjs/foo.js` would have to be promoted to `src/subdir/foo.js` and the relative requires would have to match up
   - I think supporting in-source and out of source builds simultaneously might get tricky if we're nesting the generated JS under `mel.cjs` and `mel.es6`
3. Introduce explicit ways of defining outputs, allow `.cmj` and `.js` to live in different directories.

```bash
_build/default/
  src/subdir/
    mel/
      foo.cmt
      foo.cmi
      foo.cmj
    mel.cjs/
      foo.bs.js
    mel.es6/
      foo.bs.mjs
```

**Comment by anmonteiro** [comment]
>  Before this change, it mixed two concerns: where to output the JS file, and where the JS imports are relative to.

I still think this change is correct. In the future, we can allow for further control:

- `--bs-package-specs` "pretends" where the final JS artifacts live, so that the `.JS` requires are correct
- `-o` or `--output-js` would effectively write the JS files to a hardcoded location

This separates JS (runtime) imports from where JS files live after they're compiled. In order for them to be "usable", we'd need to either "install" them with Dune (e.g. so that `src/subdir/mel.cjs/foo.js` ends up in `src/subdir/foo.js`, or make sure that `--bs-package-specs` and `-o` are in sync..)

**Comment by anmonteiro** [comment]
> But we do allow rules to introduce targets in sub directories - although this is not yet available to the dune language.

@rgrinberg I think this would be a very welcome addition, as it'd allow us to specify, e.g.:


```lisp
(rule
 (targets js.cmj js.cmi mel.cjs/js.js mel.es6/js.js)
  ...)
```

Right now it produces an error:

```
17 |  (targets js.cmj js.cmi mel.cjs/js.js mel.es6/js.js)
                                      ^^^^^^^^^^
Error: "es6/js.mjs" does not denote a file in the current directory.
```

**Pull request merged**
