### PR TITLE
Add test for go to definition breaking with modules that collide with stdlib ones

### PR DESCRIPTION
**Pull request by jchavarri**
This test exercises "go to definition" in editor integration when some library exposes a module with the same name as the stdlib ones.

It includes two `.t` files:
- One with regular OCaml syntax, where go to definition works as expected
- Another with Reason syntax and ReasonReact, where go to definition breaks for module called `Stack`. Instead of going to the custom module defined in the library, it goes to the stdlib one.

It is unclear to me where the breakage is at the moment, but we can port the test somewhere else after any findings.

### CODE REVIEW

**Comment by anmonteiro** [comment]
I investigated this a bit and found:

- reason-react isn't the culprit
- the reason-react example which was failing had `(pps melange.ppx)`
- I added that to the other example and it also fails
- the error is:

```diff
-  {
-    "file": "$TESTCASE_ROOT/lib/stack.ml",
-    "pos": {
-      "line": 1,
-      "col": 0
-    }
-  }
+  "Several source files in your path have the same name, and merlin doesn't know which is the right one: $TESTCASE_ROOT/lib/stack.ml, /Users/anmonteiro/projects/melange/_build/install/default/lib/melange/stack.mli, /Users/anmonteiro/projects/melange/_build/install/default/lib/melange/stack.ml"
```

**Comment by anmonteiro** [comment]
With the changes I made, I don't believe this is a bug anymore. The library is `(wrapped false)`, and the Stdlib comes first in the resolution

**Comment by jchavarri** [comment]
Thanks for taking a look. I see the tests are failing, I am pretty sure they were passing originally (but the commits are gone after rebasing / force pushing, and I don't trust my memory much 😅 ).

Error in opam build says:

```
# @@ -36,18 +36,15 @@ Similar to companion editor-stdlib-gotodef-reason-react.t, but for plain OCaml
#    > EOF
#  
#    $ dune build
# +  File "command line", line 1:
# +  Error: Unbound module Stdlib
# +  [1]
```

error in nix is about `ocamlmerlin` not being available.

Do you know the reason for the opam one?

**Comment by anmonteiro** [comment]
my bad, I must have done something wrong.

here's the previous commit, though: https://github.com/melange-re/melange/commit/e7807d28cd2f1131a4e248f5f494e3952f3a2501


it was working locally, let me try fixing in CI.

**Comment by anmonteiro** [comment]
Actually I just forgot to push...

**Comment by anmonteiro** [comment]
@jchavarri do you need to take another look at this one, or are we satisfied?

**Comment by jchavarri** [comment]
Looks good to me, thanks for the improvements.

**Pull request merged**
