### PR TITLE
Revert "Fix Js.String.match_ return type" because it's a breaking change with ReScript

### PR DESCRIPTION
**Pull request by jfrolich**
I think it's a good change in general, but I think we should be careful about breaking with ReScript, as it makes parallel use of both compilers impossible. Which is something companies/projects want to do to support both compilers when experimenting with melange. I would suggest when making these changes to the bindings to create a new function instead of changing the old one breaking compatibility.

This reverts commit ccceb69d85afdf7743259bb9faca6f975ebe541f.

### CODE REVIEW

**Comment by anmonteiro** [comment]
Why is this breaking ReScript compatibility? I cherry picked the commit from https://github.com/rescript-lang/rescript-compiler/pull/5070

**Comment by jchavarri** [comment]
I think what @jfrolich means is that it might become hard to track which upstream breaking changes have made it into Melange. This change in particular did not make it until ReScript v10: https://github.com/rescript-association/rescript-lang.org/issues/552.

I suggest that we start versioning Melange (maybe also publishing in opam), so that we can map Melange versions with ReScript versions somehow, e.g.

| Melange      | ReScript |
| ----------- | ----------- |
| v0.1.x      | v9.x       |
| v0.2.x   | v10.x        |
| v0.3.x   | v11.x        |
| ...   | ...        |

That way, Melange users have an easier way of tracking which breaking changes made it to the codebase, and which ReScript libraries might be supported for each version of Melange.

If the above makes sense, then we could:
- merge this PR
- publish v0.1
- revert PR
- include any other changes in ReScript v10
- start publishing v0.2 versions
- ...

@anmonteiro what do you think?

**Comment by jfrolich** [comment]
Exactly! For this particular change it's water under the bridge (we will be at rescript 10 soon). But for future breaking changes having this system would be amazing!

**Comment by anmonteiro** [comment]
Makes sense to do that. I'll try keeping those notes next time I batch a few cherry picked commits.

**Pull request closed without merging**
