### PR TITLE
ci: add opam

### PR DESCRIPTION
**Pull request by jchavarri**
~Blocked until Dune 3.5 is released.~

Adds a new workflow in CI to test opam.

### CODE REVIEW

**Review by anmonteiro — COMMENTED** [review]
Looking good, and happy to merge in the current state. I think we should also try to build the basic template (or a new opam template) and check everything works.

**Comment by jchavarri** [comment]
I have the melange-basic-template migrated to opam in https://github.com/jchavarri/melange-basic-template. I will add the template test in this PR as well. 👍

**Comment by anmonteiro** [comment]
the CI errors look like what I get when I try something other than Node.js v16

**Comment by jchavarri** [comment]
@anmonteiro thanks, all looks ok now. Template being built on both macos and ubuntu.

**Comment by jchavarri** [comment]
@anmonteiro thanks, all looks ok now. Template being built on both macos and ubuntu.

Re: the node 18 errors, I will check on another PR if we can migrate to a more recent version of `web-tree-sitter`.

**Review by anmonteiro — APPROVED** [review]
nice!

**Pull request merged**
