### PR TITLE
Align with Dune on default warnings

### LINKED ISSUE #133: align with dune on default warnings
based on profiles, related to #92

### PR DESCRIPTION
**Pull request by anmonteiro**
fixes #133 

This change aligns with Dune on the default warnings. I grabbed [Dune's default warnings](https://github.com/ocaml/dune/blob/a2d91813b6aea0a400e75586530087c1e7a72a65/src/dune_rules/ocaml_flags.ml#L15) for the dev profile.

This needs extensive testing before landing, as it's potentially a breaking change for folks' projects.

cc @TheSpyder @jchavarri  @jfrolich @johnhaley81

### CODE REVIEW

**Comment by johnhaley81** [comment]
This looks good!

**Review by EduardoRFS — APPROVED** [review]
Small PR <3
happy with a simple PR

**Comment by jchavarri** [comment]
Thanks @anmonteiro ! I need some more time, but I'll try to test this branch later today.

**Comment by jchavarri** [comment]
works great! 🚀

**Comment by TheSpyder** [comment]
Works for me - but I set my warnings to `A-4-40-41-42-43+101-102` so this probably doesn't change much about how my project compiles.

**Pull request merged**
