### PR TITLE
Support `mel.as` in `mel.obj`

### PR DESCRIPTION
**Pull request by jchavarri**
This was never supported so when having to introduce different identifiers on JS, we would have to resort back to `deriving abstract`, e.g. for the DOM props [in reason-react](https://github.com/reasonml/reason-react/commit/24ff8026f7037f5abf7ba386afa68a69059da2ea).

There would be no need to use `deriving abstract` if `mel.as` was supported in `mel.obj` which is what this PR allows.

### CODE REVIEW

**Comment by anmonteiro** [comment]
This seems to already have been supported, e.g.: https://github.com/melange-re/melange/blob/c5bf086511ed4830018e67ca63df86045dbe356d/jscomp/test/external_ppx.ml#L20-L26


There seems to be 2 use cases for `@mel.as`, and they're a bit at odds with each other (or at least a bit confusing):

### 1. the current use case, e.g.:

```ocaml
external ff : hi:int -> lo:(_[@mel.as 1]) -> _ = "" [@@mel.obj]

let u = ff ~hi:4
```

generates:

```js
// Generated by Melange
'use strict';


var u = {
  hi: 4,
  lo: 1
};

exports.u = u;
/* No side effect */
```

### 2. your proposed use case

```ocaml
external func :   foo:(string [@mel.as "bar"]) -> ...
```

generating `bar` in the object key instead of `foo`.


### Discussion

A few ways I see forward:

1. distinguish `Ptyp_any` and don't attempt to rename in that case, falling back to the previous behavior
2. use a new `@mel.rename_label` attribute (which I find ugly)
3. .. more?

**Comment by jchavarri** [comment]
Another option is to change the positioning of the attribute. I chose to annotate the type of the labelled argument because it's imo more ergonomic, but should we annotate the whole arrow type instead? e.g.

```ocaml
external ff :
  ((hi:int -> ((lo:string -> _)[@mel.as "low"]))[@mel.as "high"]) = ""
[@@mel.obj ]
```

instead of 

```ocaml
external ff : hi:(int[@mel.as "high"]) -> lo:(string[@mel.as "low"]) -> _ = ""
[@@mel.obj]
```

The first option looks way more readable in Reason syntax:

```reason
[@mel.obj]
external ff:
  [@mel.as "high"] ((~hi: int) => [@mel.as "low"] ((~lo: string) => _));
```

**Comment by anmonteiro** [comment]
I'd rather keep it on the type, then. even in reason that feels very very weird to write.

**Comment by anmonteiro** [comment]
@jchavarri given your recent constraints around React 18, would you like me to finish this PR?

**Comment by jchavarri** [comment]
Yes, I'd appreciate it. Thanks!

**Pull request merged**
