### PR TITLE
Run tests on CI with esy 

### PR DESCRIPTION
**Pull request by EduardoRFS**
Turns out that the tests already run on esy if we ignore-promoted-rules like the ones that uses `web-tree-sitter` this will works.

In the future we may use different mechanism so that ignore-promoted-rules will not be needed.

## Related

#126

### CODE REVIEW

**Comment by EduardoRFS** [comment]
If this works on Windows I will merge, because that's a miracle

**Comment by EduardoRFS** [comment]
Of course windows failed grr

**Comment by anmonteiro** [comment]
I'd be happy to merge this and mark windows as [`continue-on-error`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error)

**Comment by EduardoRFS** [comment]
@anmonteiro will fix this tomorrow, they're small patches

**Pull request merged**
